backend:
  name: git-gateway
  branch: main

media_folder: "media/"

collections:
  - name: "page"
    label: "Page"
    folder: "_pages"  
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
